version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - run:
          name: env
          command: env
      - run:
          name: chocolatey
          command: choco --version
      - run:
          name: install msys2
          command: choco install --no-progress -y msys2
      - run:
          name: pacman
          command: pacman --help
